# workflows/exchange_rate_tracker.yaml
name: exchange-rate-tracker
description: Monitors USDCOP exchange rate and alerts on significant changes
trigger:
  type: schedule
  config:
    cron: "0 * * * *"

nodes:
  - id: fetch_rate
    type: http
    config:
      url: "https://v6.exchangerate-api.com/v6/latest/USD"
      timeout: 15

  - id: extract_cop
    type: transform
    depends_on: [fetch_rate]
    config:
      input: "{{ fetch_rate }}"
      expression: "$.body.conversion_rates.COP"

  - id: load_history
    type: storage
    config:
      path: "data/exchange_history.json"
      action: read

  - id: check_change
    type: condition
    depends_on: [extract_cop, load_history]
    config:
      if: "len(load_history) == 0 or abs(extract_cop - load_history[-1]['rate']) / load_history[-1]['rate'] > 0.02"

  - id: save_history
    type: storage
    depends_on: [extract_cop, load_history]
    config:
      path: "data/exchange_history.json"
      action: append
      data:
        pair: "USDCOP"
        rate: "{{ extract_cop }}"

  - id: alert_slack
    type: alert
    depends_on: [check_change, extract_cop]
    when: "check_change == True"
    config:
      webhook_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
      message: "USDCOP rate changed significantly! Current rate: {{ extract_cop }}"
